// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_-tTZu2kR9cnNKo8-WymG8w_tZxqLwcQ',
    appId: '1:1010837962500:web:13c6edb0d437e640e69a51',
    messagingSenderId: '1010837962500',
    projectId: 'everyoungllc',
    authDomain: 'everyoungllc.firebaseapp.com',
    storageBucket: 'everyoungllc.firebasestorage.app',
    measurementId: 'G-0CHD540S33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfkl-OvCHvaEIWDJtP_Rz3nlz7p3tU6k',
    appId: '1:1010837962500:android:31c9a7ad0f115402e69a51',
    messagingSenderId: '1010837962500',
    projectId: 'everyoungllc',
    storageBucket: 'everyoungllc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOIMJLGsiWJbSnm0lVYccN9YeJ9-mystA',
    appId: '1:1010837962500:ios:123d2e1b12523e49e69a51',
    messagingSenderId: '1010837962500',
    projectId: 'everyoungllc',
    storageBucket: 'everyoungllc.firebasestorage.app',
    iosBundleId: 'com.example.foreveryoungclinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOIMJLGsiWJbSnm0lVYccN9YeJ9-mystA',
    appId: '1:1010837962500:ios:123d2e1b12523e49e69a51',
    messagingSenderId: '1010837962500',
    projectId: 'everyoungllc',
    storageBucket: 'everyoungllc.firebasestorage.app',
    iosBundleId: 'com.example.foreveryoungclinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_-tTZu2kR9cnNKo8-WymG8w_tZxqLwcQ',
    appId: '1:1010837962500:web:8e0660c65a50d92fe69a51',
    messagingSenderId: '1010837962500',
    projectId: 'everyoungllc',
    authDomain: 'everyoungllc.firebaseapp.com',
    storageBucket: 'everyoungllc.firebasestorage.app',
    measurementId: 'G-6HQ3W4X4HD',
  );
}
